# Generated by Django 3.0.7 on 2020-06-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, help_text='Image link', max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2)),
            ],
        ),
    ]
