# Generated by Django 3.0.7 on 2020-06-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200626_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=10000),
        ),
    ]
